package manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import main.Bilet;

public class BiletManager {
	private Connection connection;
	private String url = "jdbc:hsqldb:hsql://localhost/";
	private String createTableBilet = "CREATE TABLE Bilet(id_bilet int GENERATED BY DEFAULT AS IDENTITY, rodzaj varchar(100), cena double, opis varchar(500))";
	
	private PreparedStatement dodajBilet;
	private PreparedStatement usunBilet;
	private PreparedStatement usunBilety;
	private PreparedStatement edytujBilet;
	private PreparedStatement pobierzBilety;
	private Statement statement;
	
	public BiletManager(){
		try{
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while(rs.next()){
				if("Bilet".equalsIgnoreCase(rs.getString("TABLE_NAME"))){
						tableExists = true;
						break;
				}
			}
			
		if(!tableExists){
			statement.executeUpdate(createTableBilet);
		}
		
		dodajBilet = connection.prepareStatement("INSERT INTO Bilet(rodzaj, cena, opis) VALUES (?, ?, ?)"); 
		usunBilet = connection.prepareStatement("DELETE FROM Bilet where id_bilet = ?");
		usunBilety = connection.prepareStatement("DELETE FROM Bilet");
		edytujBilet = connection.prepareStatement("UPDATE Bilet set rodzaj = ?, cena = ?, opis = ? where id_bilet = ?");
		pobierzBilety = connection.prepareStatement("SELECT id_bilet, rodzaj, cena, opis FROM Bilet");
		}catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public Connection getConnection(){
		return connection;
	}
	
	public void wyczyscBilet(){
		try{
			usunBilety.executeUpdate();
		}catch(SQLException e){
			e.printStackTrace();
		}
	}
	
	public int dodajBilet(Bilet bilet){
		int licznik = 0;
		try{
			dodajBilet.setString(1, bilet.getRodzaj());
			dodajBilet.setDouble(2, bilet.getCena());
			dodajBilet.setString(3, bilet.getOpis());
			licznik = dodajBilet.executeUpdate();
		}catch(SQLException e){
			e.printStackTrace();
		}
		return licznik;
	}
	
	public int usunBilet(Bilet bilet){
		int licznik = 0;
		try{
			usunBilet.setInt(1, bilet.getId());
			licznik = usunBilet.executeUpdate();
		}catch(SQLException e){
			e.printStackTrace();
		}
		return licznik;
	}
	
	public int edytujBilet(Bilet bilet){
		int licznik = 0;
		try{
			edytujBilet.setString(1, bilet.getRodzaj());
			edytujBilet.setDouble(2, bilet.getCena());
			edytujBilet.setString(3, bilet.getOpis());
			edytujBilet.setInt(4,  bilet.getId());
			licznik = edytujBilet.executeUpdate();
		}catch(SQLException e){
			e.printStackTrace();
		}
		return licznik;
	}
	
	public List<Bilet> pobierzBilety(){
		List<Bilet> bilety = new ArrayList<Bilet>();
		try{
			ResultSet rs = pobierzBilety.executeQuery();
			while(rs.next()){
				Bilet b = new Bilet();
				b.setId(rs.getInt("id_bilet"));
				b.setRodzaj(rs.getString("rodzaj"));
				b.setCena(rs.getDouble("cena"));
				b.setOpis(rs.getString("opis"));
				bilety.add(b);
			}
		}catch(SQLException e){
			e.printStackTrace();
		}
		return bilety;
	}
}
